name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

  Security:

    runs-on: ubuntu-latest

    steps:
    - name: Trivy Installation
      run: |
          sudo apt update && sudo apt install -y snapd
          sudo snap install trivy

    - name: Verify Trivy Installation
      run: trivy --version
          
    - name: Trivy FS Scan   
      run: trivy fs --format table -o fs-report.json .


    - name: GitLeaks Installation
      run:   |
        sudo apt update && sudo apt install -y golang-go
        wget https://github.com/gitleaks/gitleaks/releases/download/v8.4.0/gitleaks-linux-amd64 -O gitleaks
        chmod +x gitleaks
        sudo mv gitleaks /usr/local/bin/gitleaks

    - name: Verify GitLeaks Installation
      run: gitleaks --version

    - name: GitLeak Code Scan
      run:  gitleaks detect --source . --report-format json --report-path gitleaks.json





      
